import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Welcome to Next.js!!!
        </h1>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe deserunt nostrum consectetur culpa molestiae ducimus omnis ullam repellat repudiandae, magnam quos hic libero fuga earum dignissimos recusandae eius consequatur est.</p>

        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur explicabo, iste dolor, cum minima consequuntur recusandae nisi fuga pariatur dolore quis impedit, sit reprehenderit non. Quasi minima dolores sunt officiis?</p>
      </main>

      <footer className={styles.footer}>
        This is The Footer
      </footer>
    </div>
  )
}
